//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Bridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Token
    {
        public int ID { get; set; }
        public string TokenValue { get; set; }
        public string UserID { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
