//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Bridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int PID { get; set; }
        public string Product { get; set; }
        public string Product_Description { get; set; }
        public Nullable<int> FK_PCID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Stock { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tbl_Product_Category tbl_Product_Category { get; set; }
    }
}
